WebRazor/Controllers/AdministracionController.cs
using GestoresLayer;
using ModelLayer.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebRazor.Models;

namespace WebRazor.Controllers
{
    public class AdministracionController : GenericController
    {
        // GET: Administracion
        public ActionResult Index()
        {
            return View();
        }

        #region paises
        public JsonResult paisesGetAll()
        {
            List<Pais> paises = PaisGestor.getAll();

            return Json(paises, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region provincias
        public JsonResult provinciasGetAllByIdPais(int id_pais)
        {
            List<Provincia> provincias = ProvinciaGestor.getAllByIdPais(id_pais);

            return Json(provincias, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region localidades
        public JsonResult localidadesGetAllByIdProvincia(int id_provincia)
        {
            List<Localidad> localidades = LocalidadGestor.getAllByIdProvincia(id_provincia);

            return Json(localidades, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region barrios
        public JsonResult barriosGetAllByIdLocalidad(int id_localidad)
        {
            List<Barrio> barrios = BarrioGestor.getAllByIdLocalidad(id_localidad);

            return Json(barrios, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region codigos colegios

        public ActionResult codigosAdmin()
        {
            Usuario usuarioActual = currentUser();

            Colegio colegio = usuarioActual.Colegio.FirstOrDefault();

            if(colegio != null)
            {
                List<Codigo_Colegio> codigos = ColegioGestor.codigosGetAllByColegio(colegio);
                List<Rol> roles = RolGestor.getAll();

                SelectList listaRoles = new SelectList(roles, "id_rol","descripcion");
                
                ViewBag.roles = listaRoles;
                return View(codigos);
            }
            else
            {
                return Redirect("/Error/HomeError?mensaje=Sesion%20Caducada");
            }
        }

        #endregion

        #region paginas

        public ActionResult paginasIndex()
        {
            List<Pagina> paginas = PaginaGestor.getAll();
            
            return View(paginas);
        }

        public ActionResult nuevaPaginaModal()
        {
            return View("Modales/nuevaPagina");
        }

        public JsonResult crearPagina(Pagina nuevaPagina)
        {
            bool error = true;
            string mensaje = "Ocurrió un error al crear la página";

            string mensajeError = string.Empty;

            try
            {
                if (PaginaGestor.crear(nuevaPagina, ref mensajeError))
                {
                    error = false;
                    mensaje = "Página creada con éxito";
                }
                else
                {
                    if (!string.IsNullOrEmpty(mensajeError))
                    {
                        mensaje = mensajeError;
                    }

                }
            }
            catch (Exception)
            {
                
            }
            

            return Json(new Respuesta { Error = error, Mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

WebRazor/Views/Administracion/Modales/nuevaPagina.cshtml
@using ModelLayer.Entities;

@model Pagina
<div class="contenido-central">
    <form>
        <div class="form-group">
            @Html.TextBoxFor(x => x.nombre, new { @class = "form-control", @placeholder = "Nombre" })
        </div>

        <div class="form-group">
            @Html.TextBoxFor(x => x.menu, new { @class = "form-control", @placeholder = "Menú" })
        </div>
        <div class="form-group">
            @Html.TextBoxFor(x => x.controlador, new { @class = "form-control", @placeholder = "Controlador" })
        </div>

        <div class="form-group">
            @Html.TextBoxFor(x => x.accion, new { @class = "form-control", @placeholder = "Acción" })
        </div>

        <div class="form-group">
            @Html.TextBoxFor(x => x.orden, new { @class = "form-control", @placeholder = "Orden" })
        </div>
        <div class="form-group">
            @Html.TextBoxFor(x => x.icono, new { @class = "form-control", @placeholder = "Icono" })
        </div>
        <div class="form-group">
            <button id="btnCrear" type="button" onclick="crearPagina()" class="btn btn-primario" style="margin-left: 55px">Crear</button>
            <button id="btnCancelar" type="button" onclick="cerrarModal()" class="btn btn-secundario pull-right" style="margin-right: 55px">Cancelar</button>
        </div>

        <div class="form-group">
            <label id="lblRespuesta"></label>
        </div>

    </form>
</div>

<script type="text/javascript">

        var nuevaPaginaParams = {
            crearURL: "@Url.Action("crearPagina", "Administracion")"
        };

</script>

<script src="~/Scripts/website/administracion/modales/nuevaPagina.js"></script>