WebRazor/Controllers/SesionController.cs
using GestoresLayer;
using ModelLayer.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utils;
using WebRazor.Models;

namespace WebRazor.Controllers
{
    public class SesionController : GenericController
    {
        // GET: Sesion
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult iniciarSesion(Usuario usuario)
        {
            try
            {
                usuario.password = MD5Utilities.GetSHA1(usuario.password);

                Usuario usuarioLogin = UsuarioGestor.validarUsuario(usuario);

                if (usuarioLogin != null && usuarioLogin.id_usuario > 0)
                {
                    //Session["idUsuario"] = usuarioLogin.id_usuario;
                    //Session["nombreUsuario"] = usuarioLogin.nombre_usuario;
                    if(usuarioLogin.Rol_Usuario != null && usuarioLogin.Rol_Usuario.Count > 0)
                    {
                        if (usuarioLogin.Colegio.Count == 0)
                        {
                            return Json(new Respuesta { Error = true, Mensaje = "No tiene un colegio asignado" }, JsonRequestBehavior.AllowGet);
                        }
                        else if (usuarioLogin.Colegio.Count == 1)
                        {
                            Session["usuario"] = usuarioLogin;
                            return Json(new Respuesta { Error = false, Mensaje = "Sesión válida" }, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                            return Json(new Respuesta { Error = true, Mensaje = "Seleccionar Colegio" }, JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        return Json(new Respuesta { Error = true, Mensaje = "Usted no tiene un perfil asignado." }, JsonRequestBehavior.AllowGet);
                    }
                }

                return Json(new Respuesta { Error = true, Mensaje = "Usuario y/o contraseña incorrectos." }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new Respuesta { Error = true, Mensaje = "Ocurrió un error inesperado." }, JsonRequestBehavior.AllowGet);
            }
            
        }

        public string CerrarSesion()
        {
            Usuario usuario = new Usuario();
            if (Session != null)
                usuario = Session["usuario"] as Usuario;
            else usuario = null;
            if (usuario != null && usuario.id_usuario != 1)
            {
                //LogHistorialEventos("Usuario", "-Cierre de sesion '" + usuario.nombre_usuario + "'-", "USE", usuario.id_usuario);
            }

            Session["usuario"] = null;
            Session["Pagina"] = null;

            Session.Clear();
            return "../Sesion/Index";
        }
    }
}

WebRazor/Controllers/UsuarioController.cs
using GestoresLayer;
using ModelLayer.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utils;
using WebRazor.Models;

namespace WebRazor.Controllers
{
    public class UsuarioController : GenericController
    {
        // GET: Usuari
        public ActionResult Index()
        {
            List<Usuario> usuarios = UsuarioGestor.getUsuariosByColegio(currentUser().Colegio.First());
            return View(usuarios);
        }

        public ActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public JsonResult registrarUsuario(Usuario usuario, string codigo_colegio)
        {
            string mensaje = string.Empty;
            if(validarDatosUsuario(ref mensaje, usuario, codigo_colegio))
            {
                Codigo_Colegio codigoColegioObj = new Codigo_Colegio();
                if(!validarCodigoColegio(codigo_colegio, ref codigoColegioObj))
                {
                    return Json(new Respuesta { Error = true, Mensaje = "El código del colegio no es válido." }, JsonRequestBehavior.AllowGet);
                }

                usuario.password = MD5Utilities.GetSHA1(usuario.password);
                string mensaje_error = string.Empty;
                if(UsuarioGestor.crear(usuario, codigoColegioObj, ref mensaje_error)) 
                {
                    return Json(new Respuesta { Error = false, Mensaje = "Usuario creado con éxito" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    if(!string.IsNullOrEmpty(mensaje_error))
                    {
                        return Json(new Respuesta { Error = true, Mensaje = mensaje_error }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new Respuesta { Error = true, Mensaje = "Ocurrió un error al registrar el usuario" }, JsonRequestBehavior.AllowGet);
                }
            }

            return Json(new Respuesta { Error = true, Mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        private bool validarCodigoColegio(string codigo_colegio, ref Codigo_Colegio codigoColegioObj)
        {
            codigoColegioObj = ColegioGestor.getByCodigo(codigo_colegio);

            return codigoColegioObj != null;
        }

        private bool validarDatosUsuario(ref string mensaje, Usuario pUser, string codigo_colegio)
        {
            if (string.IsNullOrEmpty(pUser.nombre_usuario))
            {
                mensaje = "El usuario no puede estar vacío";
                return false;
            }

            if (string.IsNullOrEmpty(pUser.password))
            {
                mensaje = "El password no puede estar vacío";
                return false;
            }

            if (string.IsNullOrEmpty(pUser.nombre))
            {
                mensaje = "El nombre no puede estar vacío";
                return false;
            }

            if (string.IsNullOrEmpty(pUser.apellido))
            {
                mensaje = "El apellido no puede estar vacío";
                return false;
            }

            if (string.IsNullOrEmpty(pUser.email))
            {
                mensaje = "El email no puede estar vacío";
                return false;
            }

            if (string.IsNullOrEmpty(pUser.celular))
            {
                mensaje = "El celular no puede estar vacío";
                return false;
            }

            if(string.IsNullOrEmpty(codigo_colegio))
            {
                mensaje = "El código del colegio no puede estar vacío";
                return false;
            }

            return true;
        }
    }
}

WebRazor/Views/Usuario/Index.cshtml
@using ModelLayer.Entities

@model List<Usuario>


<div class="form">

    <div class="pull-left valign"> <i class="fa fa-home"></i> <b>INICIO</b> </div>


    <div class="form-body" style="text-align: center">
        <table class="table">
            <thead>
                <tr>
                    <td>Nombre</td>
                    <td>Apellido</td>
                    <td>Nombre Usuario</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var rol in Model)
                {
                    <tr>
                        <td>@rol.nombre</td>
                        <td>@rol.apellido</td>
                        <td>@rol.nombre_usuario</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>



<script type="text/javascript">

        var UsuarioIndexParams = {
            paginasRolURL: "@Url.Action("verPaginas", "Usuario")"
        };

</script>

<script src="~/Scripts/website/usuario/index.js"></script>

WebRazor/Views/Usuario/Registrar.cshtml
@model ModelLayer.Entities.Usuario

@{
                /**/

                ViewBag.Title = "Registrar";
                Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<div class="header-central">
    <h1><span>Registrar Usuario</span></h1>
</div>
<div class="contenido-central">
    <form>
        <div class="form-group">
            @Html.TextBoxFor(x => x.nombre_usuario, new { @class = "form-control", @placeholder = "Usuario" })
        </div>

        <div class="form-group">
            @Html.TextBoxFor(x => x.password, new { @class = "form-control", @placeholder = "Password", @type = "password" })
        </div>
        <div class="form-group">
            @Html.TextBox("password_confirm", "", new { @class = "form-control", @placeholder = "Confirmar Password", @type = "password" })
        </div>

        <div class="form-group">
            @Html.TextBoxFor(x => x.nombre, new { @class = "form-control", @placeholder = "Nombre" })
        </div>

        <div class="form-group">
            @Html.TextBoxFor(x => x.apellido, new { @class = "form-control", @placeholder = "Apellido" })
        </div>

        <div class="form-group">
            @Html.TextBoxFor(x => x.email, new { @class = "form-control", @placeholder = "Email" })
        </div>
        <div class="form-group">
            @Html.TextBoxFor(x => x.celular, new { @class = "form-control", @placeholder = "Celular" })
        </div>
        <div class="form-group">
            @Html.TextBox("codigoColegio","",new { @class = "form-control", @placeholder = "Código del colegio" })
        </div>
        <div class="form-group">
            <button id="btnRegistrar" type="button" class="btn btn-primario" style="margin-left: 55px">Registrar</button>
            <button id="btnCancelar" type="button" class="btn btn-secundario pull-right" style="margin-right: 55px">Volver</button>
        </div>

        <div class="form-group">
            <label id="lblRespuesta"></label>
        </div>

    </form>
</div>

@section scripts{

    <script type="text/javascript">

        var RegistrarUsuarioParams = {
            registrarUsuarioURL: "@Url.Action("registrarUsuario", "Usuario")",
            volverURL: "@Url.Action("Index","Sesion")"
        };

    </script>

    <script src="~/Scripts/website/usuario/registrar.js"></script>

}